apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc3
  template:
    metadata:
      labels:
        app: cc3
    spec:
      containers:
        - name: cc3
          image: nipuntlankaiit/springboot:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
---
# Node Port Service For SpringApp
apiVersion: v1
kind: Service
metadata:
  name: cc3
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: cc3
