apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc2
  template:
    metadata:
      labels:
        app: cc2
    spec:
      containers:
        - name: cc2
          image: nipuntlankaiit/springboot:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
---
# Node Port Service For SpringApp
apiVersion: v1
kind: Service
metadata:
  name: cc2
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: cc2
