apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc1
  template:
    metadata:
      labels:
        app: cc1
    spec:
      containers:
        - name: cc1
          image: nipuntlankaiit/springboot:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
# Node Port Service For SpringApp
apiVersion: v1
kind: Service
metadata:
  name: cc1
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: cc1
